### ISSUE TITLE
Error when run with docker

### ISSUE THREAD

**Issue by Xinchungeorb** [Deeptrain-Community/Deeptrain#6]
Thanks for your code!
I want to know how to run this platform. When I ran this code through Docker on Windows 10, the following error occurred:
=> ERROR [1/6] FROM docker.io/library/python:3.9@sha256:  

Do you know how to solve this problem?

**Comment by zmh-program** [comment]
I can't reproduce your anomaly (in Ubuntu 24), could you please provide more information?
And the machine learning training feature is under development :)
