### ISSUE TITLE
Error when logging in with Github

### ISSUE THREAD

**Issue by YuanScott** [Deeptrain-Community/Deeptrain#7]
见图(非注册，非首次登录)：  

![Screenshot-at-Deeptrain](https://github.com/Deeptrain-Community/Deeptrain/assets/105967559/40c846e2-dd15-4851-b08f-f87f919b6235)

环境：firefox-esr 115.5.0, Ubuntu 22

**Comment by zmh-program** [comment]
厚，你需要感谢你伟大的 GFW。

**Comment by zmh-program** [comment]
好了，已修复。
